## Tutorial from: http://introtopython.org/

### Variables, Strings, and Numbers

In [5]:
print "Hello World\n"

Hello World

In [1]:
message = "Hello Jeet from Python world!"
print(message)

Hello Jeet from Python world!

In [2]:
first_name = 'jeet'
print(first_name)
print(first_name.title())
print(first_name.upper())

jeet
Jeet
JEET

#### variable_name.action()

In this example, the word "action" is the name of a method. A method is something that can be done to a variable. The methods 'lower', 'title', and 'upper' are all functions that have been written into the Python language, which do something to strings. Later on, you will learn to write your own methods.

### Concatenate strings

In [5]:
first_name = 'ada'
last_name = 'lovelace'
full_name = first_name + ' ' + last_name
message = full_name.title() + ' ' + "was considered the world's first computer programmer."
print(message)

Ada Lovelace was considered the world's first computer programmer.

### Stripping whitespace
Many times you will allow users to enter text into a box, and then you will read that text and use it. It is really easy for people to include extra whitespace at the beginning or end of their text. Whitespace includes spaces, tabs, and newlines.

It is often a good idea to strip this whitespace from strings before you start working with them. For example, you might want to let people log in, and you probably want to treat 'eric ' as 'eric' when you are trying to see if I exist on your system.

You can strip whitespace from the left side, the right side, or both sides of a string.

In [14]:
name = ' eric '

print('-' + name.lstrip() + '-')
print('-' + name.rstrip() + '-')
print('-' + name.strip() + '-')

-eric -
- eric-
-eric-

### Numbers

In [7]:
print 4/2
print 0.1+0.2
print float(3.0/2)
print (3/2)

2
0.3
1.5
1

In [17]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

## Lists & Tuples

In [8]:
students = ['ellen','richie','george','Jeet']

In [9]:
students

['ellen', 'richie', 'george', 'Jeet']

In [11]:
for student in students:
    print "Hello, "+ student.title() + '!!'

Hello, Ellen!!
Hello, Richie!!
Hello, George!!
Hello, Jeet!!

### Enumeration

In [15]:
dogs = ['Neha','Jeet','Nysa', 'Ari']

print("Results for the dog show are as follows:\n")
for index, dog in enumerate(dogs):
    place = str(index + 1)
    print("Place: " + place + " Dog: " + dog.title())

Results for the dog show are as follows:

Place: 1 Dog: Neha
Place: 2 Dog: Jeet
Place: 3 Dog: Nysa
Place: 4 Dog: Ari

### Sorting Vs. Sorted

In [30]:
students = ['bernice', 'aaron', 'cody']

# Display students in alphabetical order, but keep the original order.
print("Here is the list in alphabetical order:")
for student in sorted(students):
    print(student.title())

# Display students in reverse alphabetical order, but keep the original order.
print("\nHere is the list in reverse alphabetical order:")
for student in sorted(students, reverse=True):
    print(student.title())

print("\nHere is the list in its original order:")
# Show that the list is still in its original order.
for student in students:
    print(student.title())

Here is the list in alphabetical order:
Aaron
Bernice
Cody

Here is the list in reverse alphabetical order:
Cody
Bernice
Aaron

Here is the list in its original order:
Bernice
Aaron
Cody

### Slicing Lists

In [21]:
usernames = ['bernice', 'cody', 'aaron', 'ever', 'dalia']

# Grab the first three users in the list.
first_batch = usernames[:3]
print first_batch
for user in first_batch:
    print(user.title())
    
ages = [23, 16, 14, 28, 19, 11, 38]

youngest = min(ages)
oldest = max(ages)
total_years = sum(ages)
print("Our youngest reader is " + str(youngest) + " years old.")
print("Our oldest reader is " + str(oldest) + " years old.")
print("Together, we have " + str(total_years) + " years worth of life experience.")

['bernice', 'cody', 'aaron']
Bernice
Cody
Aaron
Our youngest reader is 11 years old.
Our oldest reader is 38 years old.
Together, we have 149 years worth of life experience.

### List comprehensions

In [ ]:
squares = [number**2 for number in range(1,11)]
print range(1,11,3)

evens = [number for number in range(0,11,2)]
print evens

# Consider some students.
students = ['bernice', 'aaron', 'cody']
# Let's turn them into great students.
great_students = [student.title() + " the great!" for student in students]
print(great_students)

### Starting Functions

In [34]:
def say_hello(name):
    print ("Hello " + name + " this is my first function!")
    
say_hello("Jeet")

def say_hi(name):
    print ("Hi " + name.title() + "!")

say_hi("Neha")

Hello Jeet this is my first function!
Hi Neha!

In [69]:
def number_to_word(number):
    if number == 0:
        return "zero"
    if number == 1:
        return "one"
    if number == 3:
        return "three"
    else:
        return "Sorry, I don't know this number!"

for number in range(5):
    word = number_to_word(number)
    print("Number %s spells as %s" %(str(number), word))

Number 0 spells as zero
Number 1 spells as one
Number 2 spells as Sorry, I don't know this number!
Number 3 spells as three
Number 4 spells as Sorry, I don't know this number!

In [41]:
desserts = ['ice cream', 'chocolate', 'apple crisp', 'cookies']
favorite_dessert = 'apple crisp'

for dessert in desserts:
    if dessert == favorite_dessert:
        print("%s is my favorite desert" % dessert.title())
    else:
        print("I like %s" % dessert.title())

I like Ice Cream
I like Chocolate
Apple Crisp is my favorite desert
I like Cookies

### Pandas

In [7]:
import pandas as pd
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]});
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [9]:
df.loc[df.AAA >5,'BBB'] = -1
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   -1  -30
3    7   -1  -50

In [10]:
df_mask = pd.DataFrame({'AAA' : [True] * 4, 'BBB' : [False] * 4,'CCC' : [True,False] * 2})
df_mask

    AAA    BBB    CCC
0  True  False   True
1  True  False  False
2  True  False   True
3  True  False  False

In [12]:
df.where(df_mask,-1000)

   AAA   BBB   CCC
0    4 -1000   100
1    5 -1000 -1000
2    6 -1000   -30
3    7 -1000 -1000

In [19]:
import numpy as np
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]})
print df
df['logic'] = np.where(df['AAA'] > 5,'high','low')
print df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50
   AAA  BBB  CCC logic
0    4   10  100   low
1    5   20   50   low
2    6   30  -30  high
3    7   40  -50  high

In [25]:
dflow = df[df.AAA <= 5]
print dflow
dfhigh = df[df.AAA > 5]
print dfhigh

   AAA  BBB  CCC logic
0    4   10  100   low
1    5   20   50   low
   AAA  BBB  CCC logic
2    6   30  -30  high
3    7   40  -50  high